import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./providers/ReduxProvider";
import AuthProvider from "./providers/AuthProvider";
import Navbar from "./Component/navbar";
import Footer from "./Component/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <AuthProvider>
            <Navbar></Navbar>
            
          <div className="min-h-[calc(100vh-8rem)] h-full">
          {children}
          </div>
          <Footer></Footer>
            </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
