import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./providers/ReduxProvider";
import AuthProvider from "./providers/AuthProvider";
import Navbar from "./Component/navbar";
import Footer from "./Component/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Build Master",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        <ReduxProvider>
          <AuthProvider>
            <div className="sticky top-0 z-10">
              <Navbar></Navbar>
            </div>
            <div className="min-h-[calc(100vh-8rem)] h-full">{children}</div>
            <Footer></Footer>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
